# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  create_branch:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          git branch my_branch
          git checkout my_branch
          git push --set-upstream origin my_branch
      
  add_files:
    runs-on: ubuntu-latest
    needs: create_branch
    
    strategy:
      matrix:
        pfx: [ 0, 1, 2, 3]
    
    steps:
      - uses: actions/checkout@v2
        with:
          ref: my_branch
      
      - run: |
          echo ${{ matrix.pfx }} > ${{ matrix.pfx }}.txt
        
      - run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add .
          git commit -m "add ${{ matrix.pfx }}.txt"
          for retry in {1..10}
            do
             git pull --rebase
             git push && break
             sleep $[ ( $RANDOM % 10 ) + 1]
          done
  concat_files:
    runs-on: ubuntu-latest
    needs: add_files
    
    steps:
      - uses: actions/checkout@v2
        with:
          ref: my_branch
      
      - run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          cat *.txt > out.txt
          rm 0.txt 1.txt 2.txt 3.txt
          git add .
          git commit -m "replace individual files"
      
      - run: |
          git fetch
          git checkout main
          git merge --squash my_branch
          git commit -m "merge squashed my_branch"
          git push && git push -d origin my_branch && git branch -d my_branch
