# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  create_branch:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          git branch my_branch
          git checkout my_branch
          git push --set-upstream origin my_branch
      
  add_files:
    runs-on: ubuntu-latest
    needs: create_branch
    
    strategy:
      matrix:
        pfx: [ 0, 1, 2, 3]
    
    steps:
      - uses: actions/checkout@v2
        with:
          ref: my_branch
      
      - run: |
          echo ${{ matrix.pfx }} > ${{ matrix.pfx }}.txt
        
      - run: |
          git add .
          git commit -m "add ${{ matrix.pfx }}.txt"
          git pull --rebase
          git push

  concat_files:
    runs-on: ubuntu-latest
    needs: add_files
    
    steps:
      - uses: actions/checkout@v2
        with:
          ref: my_branch
      
      - run: |
          cat *.txt > out.txt
          rm 0.txt 1.txt 2.txt 3.txt
          git add .
          git commit -m "replace individual files"
          git push

